# Generated by Django 4.0.4 on 2022-04-27 05:59

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_applicant_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(blank=True, help_text='PDF only', upload_to='private/resumes', validators=[jobs.models.validate_pdf]),
        ),
    ]
