# Generated by Django 4.0.4 on 2022-04-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagesApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Joke',
        ),
    ]
