# Generated by Django 4.0.4 on 2022-04-25 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0006_tag_joke_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag'], 'verbose_name_plural': 'Tags'},
        ),
    ]
